### PR TITLE
feat: polling for updates in JoinLobby activity

### PR DESCRIPTION
**Pull request by FRALEXAlexander**

### CODE REVIEW

**Review by BenjaminHac-Edu — CHANGES_REQUESTED** [review]
Private lobbies got also fetched by the call so that they are also shown in Join Lobby

**Comment by FRALEXAlexander** [comment]
A fix for this needs to be done in the backend

**Comment by TannerGabriel** [comment]
> A fix for this needs to be done in the backend

You should probably be able to filter it in `onSuccessGetLobbies`

**Comment by FRALEXAlexander** [comment]
Fixed in https://github.com/SE2Project-BHKPTZ/backend/pull/49

**Review by TannerGabriel — APPROVED** [review]

**Review by BenjaminHac-Edu — APPROVED** [review]
LGTM

**Pull request merged**
