### PR TITLE
feat: redesign main activity

### PR DESCRIPTION
**Pull request by BenjaminHac-Edu**

### CODE REVIEW

**Comment by BenjaminHac-Edu** [comment]
I will probably use this branch to redesign the complete UI app.

**Comment by FRALEXAlexander** [comment]
Clicking on join Lobby sometimes brings me to the create lobby

**Comment by BenjaminHac-Edu** [comment]
> Clicking on join Lobby sometimes brings me to the create lobby

I am not able to reproduce/detect this bug. It works for me correct

**Comment by FRALEXAlexander** [comment]
Could have been a local problem on my site.

**Review by FRALEXAlexander — APPROVED** [review]
LGTM

**Pull request merged**
