### PR TITLE
feat: play card

### LINKED ISSUE #38: Play Card
A player should be able to play one of their hand cards

## Definition of done

- [x] player play one of their hand cards by clicking (or other gesture)
- [x] the card played should appear on the game screen
- [x] the card played is no longer on the hand
- [x] it should only be possible to play a card when there is no card on the game screen.

### PR DESCRIPTION
**Pull request by BenjaminHac-Edu**
# Closes
#38

### CODE REVIEW

**Comment by BenjaminHac-Edu** [comment]
There is a bug after playing a card and changing the fragment. 
In the 3rd round, the hand is no longer correct after the play. Another card is shown twice and another card is also removed.

Maybe you have a solution, I don't have a clue yet

**Comment by TannerGabriel** [comment]
> There is a bug after playing a card and changing the fragment. In the 3rd round, the hand is no longer correct after the play. Another card is shown twice and another card is also removed.
> 
> Maybe you have a solution, I don't have a clue yet

The bug seems to happen since the `RecyclerView` does not re-render correctly (no clue why it happens only starting with the thrid round). Normally we should be able to use `notifyItemRemoved` and `notifyItemChanged` (see example below), but that didn't work for me here, so I had to use `notifyDataSetChanged`, which seems to fix the error.

```
// Does not work
adapter.removeCard(cardItem, position)
adapter.notifyItemRemoved(position)
val itemChangedCount = adapter.itemCount - position
adapter.notifyItemRangeChanged(position, itemChangedCount)

// Seems to work
adapter.notifyDataSetChanged()
```

**Comment by BenjaminHac-Edu** [comment]
> adapter.notifyDataSetChanged()

ty, it works now

**Review by TannerGabriel — CHANGES_REQUESTED** [review]
It looks good (scrolling also works on an actual phone), but please remove the border animation for the cards since it is not needed with the current solution.

**Review by TannerGabriel — APPROVED** [review]

**Pull request merged**
