### PR TITLE
feat: first card played restrictions

### LINKED ISSUE #57: Non-playable cards
In Wizard the playable cards depends on the first played card. 
- A wizard or a jester can always be played
- Jester at the beginning of a trick have no influence on what follows.
- If the first card of a trick (after possible jesters) is a wizard, any card can be played afterwards.
- Otherwise, the colour of the first non-jester card is the one that must be played (this can also be the trump suit): Every player who has at least one card of this colour in their hand must play one. Anyone who does not have the required colour may play any other card.

## Definition of done

- [ ] The above mentioned features are implemented
- [ ] Either non-playable or playable cards shall be highlighted

### PR DESCRIPTION
**Pull request by BenjaminHac-Edu**
closes #57

### CODE REVIEW

**Comment by BenjaminHac-Edu** [comment]
should we add a new card background, in order to do not have the same card highlight background for playable and current winner cards?

**Comment by TannerGabriel** [comment]
> should we add a new card background, in order to do not have the same card highlight background for playable and current winner cards?

Would definitely make sense

**Comment by TannerGabriel** [comment]
He should also be able to play the trump in this case.
Screenshot_2024-05-27-09-50-42_7760x3840

**Comment by BenjaminHac-Edu** [comment]
> He should also be able to play the trump in this case. Screenshot_2024-05-27-09-50-42_7760x3840

I don't think so. You have to follow the first card suit played, even if they have a trump card. Only Wizard or Jester can always be played. At least that's how I understood the rules.

**Review by TannerGabriel — APPROVED** [review]
You are right. LGTM

**Pull request merged**
