### PR TITLE
feat: Add Sonarcloud and Jacoco config

### PR DESCRIPTION
**Pull request by TannerGabriel**
## This PR

- Adds Jacoco and Sonarcloud configuration to `build.gradle` 
- Add Github action to run Sonarcloud on PRs and on the main branch

Part of: #2

### CODE REVIEW

**Review by BenjaminHac-Edu — APPROVED** [review]
LGTM

Any idea why I can't see your feature branch on Github or in Android Studio?

**Review by BenjaminHac-Edu — APPROVED** [review]
forgot to cross the changes

**Comment by FRALEXAlexander** [comment]
@TannerGabriel is the `.idea` folder needed?

**Comment by TannerGabriel** [comment]
> @TannerGabriel is the `.idea` folder needed?

Not really, but this is the default `.gitignore` that is added when creating an Android project. If you want I can add the complete `.idea` folder to the `gitignore` and remove the files that are already in the repo.

**Comment by FRALEXAlexander** [comment]
If they are not needed it would be good to do that

**Review by FRALEXAlexander — APPROVED** [review]
LGTM

**Pull request merged**
